#!/usr/bin/env python -B
import argparse
import argcomplete
import imp
import os

pathname = os.path.dirname(os.path.abspath(__file__))
DSET = os.path.join(os.path.abspath(pathname), 'dset')
dset = imp.load_source('dset', DSET)

parser = argparse.ArgumentParser(description='Enter container\'s bash session.')
parser.add_argument("--root", help="run as root", dest='root', action='store_true')
parser.set_defaults(root=False)
parser.add_argument("container", help="container name", nargs='?')
argcomplete.autocomplete(parser)
args = parser.parse_args()

user = "--user root" if args.root else ""
container = dset.get_container_param(args.container)
dset.call("docker exec {} -it {}_{}_1 bash".format(user, dset.compose_project(), container))
