#!/bin/bash

docker volume prune -f
docker image prune -f
docker container prune -f
docker network prune -f

# todo: remove stopped containers when special option is passed
# docker rm $(docker ps -a | grep Exited | awk '{print $1;}')
