#!/usr/bin/env python
import argcomplete
import argparse
import imp
import os

pathname = os.path.dirname(os.path.abspath(__file__))
DSET = os.path.join(os.path.abspath(pathname), 'dset')
dset = imp.load_source('dset', DSET) 
DCONTAINER = os.path.join(os.path.abspath(pathname), 'dcontainer')
dcontainer = imp.load_source('dcontainer', DCONTAINER)

parser = argparse.ArgumentParser(description='Prints container\'s logs.')
parser.add_argument("container", help="container name", nargs='?')
argcomplete.autocomplete(parser)
args = parser.parse_args()

container = dset.get_container_param(args.container)
dset.call("docker exec -it {} dlog".format(dcontainer.get_container(args.container[0])))
