#!/usr/bin/python -B
import imp
import os
import sys

pathname = os.path.dirname(os.path.abspath(__file__))
DSET = os.path.join(os.path.abspath(pathname), 'dset')
dset = imp.load_source('dset', DSET) 

dset.call("docker exec -it {}_{}_1 dlog".format(dset.compose_project(), dset.get_container()))
