#!/usr/bin/env python
import argcomplete
import argparse
import imp
import os

pathname = os.path.dirname(os.path.abspath(__file__))
DSET = os.path.join(os.path.abspath(pathname), 'dset')
dset = imp.load_source('dset', DSET)

parser = argparse.ArgumentParser(description='Start a docker container. Without argument, all containers are started.')
parser.add_argument("container", help="container name", nargs='*')
argcomplete.autocomplete(parser)
args = parser.parse_args()

if not bool(args.container):
        print "Starting all containers..."
        dset.call("docker-compose {} start".format(dset.docker_compose_params()))

for container in args.container:
        dset.call("docker start {}_{}_1".format(dset.compose_project(), container))
